name: Deploy NodeJS to Cloud Foundry
on:
  push:
    paths:
    - 'BTP/cf_nodejs/**'
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name : Setup CF PUSH 
        uses: rangulvers/cf-push@main
        with:
          appdir:   './BTP/cf_nodejs/testapp'
          api:      ${{ secrets.CF_API }}
          org:      ${{ secrets.CF_ORG }}
          space:    ${{ secrets.CF_SPACE }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          manifest: manifest.yml
          validate: true
